### ISSUE TITLE
Problem with bot

### ISSUE THREAD

**Issue by Mr4sR** [KevinHendrews/NoSlots#1]
@KevY007  The bot is exposed to "spectate" anti-cheat and if it enters a rather good server, it can't enter and fixed name for 0.3.7 doesn't work

**Comment by KevY007** [comment]
I dropped this project because of lack of motivation and usefulness. SA:MP based development generally stopped interesting me so I just released all my side projects without any intention to continue or update and this is one of them. If you need to fix it, then figure it out yourself. You may have to constantly send OnfootData or send spawn RPC's through every bot's RakNet to stop them from "spectating", their 'state' has to change.
